import discord
import asyncio
import requests
import io
from logger import log

class DiscordLogClient:
    def __init__(self):pass
    def write(*msg):pass
    def log(*msg):pass

class DiscordBotLog(DiscordLogClient):
    def __init__(self, TOKEN, target_type, target_id):
        self.TOKEN = TOKEN
        self.target_type = target_type
        self.target_id = target_id
        self.client = None
        self.log = self.write

    async def _send(self, message_formatted, text_as_file=None):
        # print(f"Hellooo, instance of DiscordWebhookLog is trying to send message '{message_formatted}' to bot {self.TOKEN}")
        # Generated by Gemini3
        intents = discord.Intents.default()
        if self.client is None or self.client.is_closed():
            self.client = discord.Client(intents=intents)

        @self.client.event
        async def on_ready():
            try:
                if self.target_type == "CHANNEL":
                    target = self.client.get_channel(int(self.target_id))
                    if not target:
                        target = await self.client.fetch_channel(int(self.target_id))
                elif self.target_type == "USER":
                    target = await self.client.fetch_user(int(self.target_id))
                
                if target:
                    files = []
                    if text_as_file:
                        file_data = io.BytesIO(text_as_file.encode('utf-8'))
                        files = [discord.File(file_data, filename="content.html")]
                    await target.send(message_formatted, files=files)
            except Exception as e:
                log(f"Discord send error: {e}")
            finally:
                await self.client.close()
        
        await self.client.start(self.TOKEN)

    def write(self, *msg, text_as_file=None):
        message = " ".join(map(str, msg))
        asyncio.run(self._send(message, text_as_file=text_as_file))

class DiscordWebhookLog(DiscordLogClient):
    def __init__(self, URL, webhook_username):
        self.URL = URL
        self.webhook_username = webhook_username
        self.log = self.write

    def _send(self, *msg, text_as_file=None):
        # print(f"Hellooo, instance of DiscordWebhookLog is trying to send message '{" ".join(msg)}' to url {self.URL}")
        data = {
            "username": self.webhook_username,
            "content": " ".join(map(str, msg))
        }
        files = None
        if text_as_file is not None:
            file_data = io.BytesIO(text_as_file.encode('utf-8'))
            files = {"file": ("content.html", file_data)}
        try:
            if files:
                response = requests.post(self.URL, data=data, files=files)
            else:
                response = requests.post(self.URL, json=data)
        except requests.ConnectionError as e:
            log(f"Error sending message to discord webhook: {e}")
            return
        try:
            response.raise_for_status()
        except requests.exceptions.HTTPError as err:
            log(f"Error sending discord message: {err}")

    def write(self, *msg, text_as_file=None):
        message = " ".join(map(str, msg))
        self._send(message, text_as_file=text_as_file)
        

def send_message(client, session: aiohttp.ClientSession, targets:list[dict], message=None):
    log(f"Sending message `{message}` to targets: {targets}")
    if not targets:
        return

    for target in targets:
        target_id = target.get("target_id")
        target_type = target.get("target_type")
        
        try:
            if target_type == "USER":
                if not client:
                    log(f"Error: Cannot send to USER {target_id} because Discord client is not initialized.")
                    continue
                
                # Check cache first, then fetch
                user = client.get_user(int(target_id))
                if not user:
                    try:
                        user = client.fetch_user(int(target_id))
                    except (discord.NotFound, ValueError):
                        log(f"Error: User with ID {target_id} not found or invalid ID.")
                        continue
                    except discord.HTTPException as e:
                        log(f"Error: Failed to fetch user {target_id} from Discord API: {e}")
                        continue
                
                if user:
                    user.send(message)
                else:
                    log(f"Error: Could not retrieve user {target_id}")

            elif target_type == "CHANNEL":
                if not client:
                    log(f"Error: Cannot send to CHANNEL {target_id} because Discord client is not initialized.")
                    continue

                channel = client.get_channel(int(target_id))
                if not channel:
                    try:
                        channel = client.fetch_channel(int(target_id))
                    except (discord.NotFound, ValueError):
                        log(f"Error: Channel with ID {target_id} not found or invalid ID.")
                        continue
                    except discord.HTTPException as e:
                        log(f"Error: Failed to fetch channel {target_id} from Discord API: {e}")
                        continue
                
                if channel:
                   channel.send(message)
                else:
                    log(f"Error: Could not retrieve channel {target_id}")

            elif target_type == "WEBHOOK":
                try:
                    username = target.get('bot_name', "Website monitor")
                    data = {"content": message, "username": username}
                    with session.post(target_id, json=data) as response:
                        response.raise_for_status()
                except (aiohttp.ClientError, asyncio.TimeoutError) as http_error:
                    log(f"Error sending message to webhook {target_id}: {http_error}")
                except Exception as e:
                    log(f"Error sending message to webhook {target_id}: {e}")
            else:
                log(f"Error: Unknown target type: {target_type}")

        except Exception as e:
            log(f"Unexpected error sending message to {target_type} ({target_id}): {e}")
